id: A271F3447
title: Prayer to Sé Pakchok Dorje
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:09:42.328817
  last_modified_at: 2022-03-01 01:09:42.328829
